#!/usr/bin/env python3
"""Generate the tap formula from the exact release checksums."""
import argparse
import pathlib
import re

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("version")
parser.add_argument("checksums", type=pathlib.Path)
parser.add_argument("output", type=pathlib.Path)
args = parser.parse_args()
if not re.fullmatch(r"v\d+\.\d+\.\d+", args.version):
    parser.error("Homebrew requires a stable vX.Y.Z release")
hashes = {}
for line in args.checksums.read_text().splitlines():
    fields = line.split()
    if len(fields) != 2:
        continue
    digest, name = fields
    if name in hashes or not re.fullmatch(r"[a-f0-9]{64}", digest):
        parser.error("invalid or duplicate checksum")
    hashes[name] = digest
lines = [
    "# Generated by OwnCode's release workflow. Do not edit checksums manually.",
    "class Owncode < Formula",
    '  desc "Terminal coding agent with orchestration and context compaction"',
    '  homepage "https://github.com/muratmirgun/owncode"',
    f'  version "{args.version[1:]}"',
    '  license "MIT"',
    "",
]
for system, asset_os in [("macos", "mac"), ("linux", "linux")]:
    lines.append(f"  on_{system} do")
    for cpu, asset_arch in [("arm", "arm64"), ("intel", "x86_64")]:
        asset = f"owncode-{asset_os}-{asset_arch}.tar.gz"
        if asset not in hashes:
            parser.error(f"missing archive checksum: {asset}")
        lines.extend([
            f"    on_{cpu} do",
            f'      url "https://github.com/muratmirgun/owncode/releases/download/{args.version}/{asset}"',
            f'      sha256 "{hashes[asset]}"',
            "    end",
        ])
    lines.extend(["  end", ""])
lines.extend([
    '  depends_on "git"',
    "",
    "  def install",
    '    bin.install "owncode"',
    "  end",
    "",
    "  test do",
    '    assert_match version.to_s, shell_output("#{bin}/owncode --version")',
    "  end",
    "end",
])
args.output.parent.mkdir(parents=True, exist_ok=True)
args.output.write_text("\n".join(lines) + "\n")
